/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pif.desktop.TELAS;

import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Timer;
import java.util.TimerTask;
import javax.imageio.ImageIO;
import javax.swing.JTextField;
import pif.desktop.Classes.Cliente;
import pif.desktop.Classes.Colab;
import pif.desktop.Classes.Contato;
import pif.desktop.Classes.Equipamento;
import pif.desktop.Classes.FormatacaoStrings;
import pif.desktop.Classes.OS;
import pif.desktop.Classes.VerificacaoStrings;
import pif.desktop.DAO.CadastroDAO;
import pif.desktop.DAO.Conexao;

/**
 *
 * @author arthu
 */
public class C_OS_TELA extends javax.swing.JFrame {

    /**
     * @return the id
     */
    public javax.swing.JLabel getId() {
        return txtNomeColab;
    }

    /**
     * @param id the id to set
     */
    public void setId(javax.swing.JLabel id) {
        this.txtNomeColab = id;
    }

    /**
     * @return the idDoUser
     */
    public int getIdDoUser() {
        return idDoUser;
    }

    /**
     * @param idDoUser the idDoUser to set
     */
    public void setIdDoUser(int idDoUser) {
        this.idDoUser = idDoUser;
    }

    /**
     * @return the RUD_OS
     */
    public static RUD_OS_TELA getRUD_OS() {
        return RUD_OS;
    }

    /**
     * @return the C_OS
     */
    public static C_OS_TELA getC_OS() {
        return C_OS;
    }

    Image icon;
    private static int idDoUser;
    private TelaUtils u = new TelaUtils();
    private static RUD_OS_TELA RUD_OS = new RUD_OS_TELA();
    private static C_OS_TELA C_OS = new C_OS_TELA();
    private FormatacaoStrings fs = new FormatacaoStrings();
    private VerificacaoStrings vs = new VerificacaoStrings();

//    private static RUD_EQUIP_TELA RUD_EQUIP = new RUD_EQUIP_TELA();
//    private static C_EQUIP_TELA C_EQUIP = new C_EQUIP_TELA();
//
//    public static RUD_TEC_TELA RUD_TEC = new RUD_TEC_TELA();
//    public static C_TEC_TELA C_TEC = new C_TEC_TELA();
//
//    public static RUD_CLIENTE_TELA RUD_CLIENTE = new RUD_CLIENTE_TELA();
//    public static C_CLIENTE_TELA C_CLIENTE = new C_CLIENTE_TELA();

    /**
     * Creates new form CADASTRAR_OS
     */
    public C_OS_TELA() {
        try {
            icon = ImageIO.read(new File("src/resources/icon.png"));           
        } catch (IOException e) {
            e.printStackTrace();
        }      
        initComponents();
        painelDeRolagem.getVerticalScrollBar().setUnitIncrement(8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        painelSeções = new javax.swing.JPanel();
        btnIrOS = new javax.swing.JButton();
        btnIrEquipamentos = new javax.swing.JButton();
        btnIrTecnicos = new javax.swing.JButton();
        btnIrClientes = new javax.swing.JButton();
        painelCRUD = new javax.swing.JPanel();
        btnIrCadastroOS = new javax.swing.JButton();
        btnIrCadastroOS1 = new javax.swing.JButton();
        txtNomeColab = new javax.swing.JLabel();
        painelDeRolagem = new javax.swing.JScrollPane();
        painelDoScroll = new javax.swing.JPanel();
        painelDoFormulario = new javax.swing.JPanel();
        titleNumeroOS = new javax.swing.JLabel();
        txtNumeroOS = new javax.swing.JLabel();
        checkClienteJaCadastrado = new javax.swing.JCheckBox();
        titleCpfOuCnpj = new javax.swing.JLabel();
        titleNomeOuRazao = new javax.swing.JLabel();
        campoCpfOuCnpj = new javax.swing.JTextField();
        campoNomeOuRazao = new javax.swing.JTextField();
        titleSobrenomeOuFantasia = new javax.swing.JLabel();
        titleRgOuIe = new javax.swing.JLabel();
        campoRgOuIe = new javax.swing.JTextField();
        campoSobrenomeOuFantasia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        titleEmail = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        titleNumTel1 = new javax.swing.JLabel();
        campoNumTel1 = new javax.swing.JTextField();
        titleNumTel2 = new javax.swing.JLabel();
        campoNumTel2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        titleEstado = new javax.swing.JLabel();
        titleCep = new javax.swing.JLabel();
        campoCep = new javax.swing.JTextField();
        titleCidade = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        caixaCombinacaoEstado = new javax.swing.JComboBox<>();
        titleBairro = new javax.swing.JLabel();
        campoBairro = new javax.swing.JTextField();
        titleLograd = new javax.swing.JLabel();
        campoLograd = new javax.swing.JTextField();
        titleLogradNum = new javax.swing.JLabel();
        campoLogradNum = new javax.swing.JTextField();
        titleLogradComp = new javax.swing.JLabel();
        campoLogradComp = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        titleEquipTipo = new javax.swing.JLabel();
        campoEquipTipo = new javax.swing.JTextField();
        titleEquipMarca = new javax.swing.JLabel();
        campoEquipMarca = new javax.swing.JTextField();
        titleEquipModelo = new javax.swing.JLabel();
        campoEquipModelo = new javax.swing.JTextField();
        titleEquipNsOuImei = new javax.swing.JLabel();
        campoEquipNsOuImei = new javax.swing.JTextField();
        titleEquipAcessorios = new javax.swing.JLabel();
        titleEquipDefeitoCliente = new javax.swing.JLabel();
        campoEquipAcessorios = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        campoEquipDefeitoCliente = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        campoEquipObservacoes = new javax.swing.JTextArea();
        titleEquipObservacoes = new javax.swing.JLabel();
        titlePrevisaoSaida = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        campoPrevisaoSaida = new javax.swing.JTextField();
        titleOrcamentoAtual = new javax.swing.JLabel();
        campoOrcamentoAtual = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtErroEquipPrevisaoSaida = new javax.swing.JLabel();
        txtErroLogradNum = new javax.swing.JLabel();
        txtErroEstado = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtErroEquipOrcamento = new javax.swing.JLabel();
        txtErroEquipObservacoes = new javax.swing.JLabel();
        txtErroEquipDefeitoCliente = new javax.swing.JLabel();
        txtErroEquipAcessorios = new javax.swing.JLabel();
        txtErroEquipNsOuImei = new javax.swing.JLabel();
        txtErroEquipModelo = new javax.swing.JLabel();
        txtErroEquipMarca = new javax.swing.JLabel();
        txtErroEquipTipo = new javax.swing.JLabel();
        txtErroLogradComp = new javax.swing.JLabel();
        txtErroLograd = new javax.swing.JLabel();
        txtErroBairro = new javax.swing.JLabel();
        txtErroCidade = new javax.swing.JLabel();
        txtErroCep = new javax.swing.JLabel();
        txtErroNumTel2 = new javax.swing.JLabel();
        txtErroNumTel1 = new javax.swing.JLabel();
        txtErroEmail = new javax.swing.JLabel();
        txtErroSobrenomeOuFantasia = new javax.swing.JLabel();
        txtErroNomeOuRazao = new javax.swing.JLabel();
        txtErroRgOuIe = new javax.swing.JLabel();
        txtErroCpfOuCnpj = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(icon);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        painelSeções.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 40, 40)), "Para qual seção deseja ir?", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnIrOS.setBackground(new java.awt.Color(100, 0, 0));
        btnIrOS.setForeground(new java.awt.Color(255, 255, 255));
        btnIrOS.setText("Ordem de serviço");
        btnIrOS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 0, 0)));
        btnIrOS.setContentAreaFilled(false);
        btnIrOS.setFocusPainted(false);
        btnIrOS.setOpaque(true);
        btnIrOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                irCadastroOS(evt);
            }
        });

        btnIrEquipamentos.setBackground(new java.awt.Color(204, 0, 0));
        btnIrEquipamentos.setForeground(new java.awt.Color(255, 255, 255));
        btnIrEquipamentos.setText("Equipamentos");
        btnIrEquipamentos.setToolTipText("");
        btnIrEquipamentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrEquipamentos.setContentAreaFilled(false);
        btnIrEquipamentos.setFocusPainted(false);
        btnIrEquipamentos.setOpaque(true);
        btnIrEquipamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                irCadastroEquip(evt);
            }
        });

        btnIrTecnicos.setBackground(new java.awt.Color(204, 0, 0));
        btnIrTecnicos.setForeground(new java.awt.Color(255, 255, 255));
        btnIrTecnicos.setText("Técnicos");
        btnIrTecnicos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrTecnicos.setContentAreaFilled(false);
        btnIrTecnicos.setFocusPainted(false);
        btnIrTecnicos.setOpaque(true);
        btnIrTecnicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                irCadastroTec(evt);
            }
        });

        btnIrClientes.setBackground(new java.awt.Color(204, 0, 0));
        btnIrClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnIrClientes.setText("Clientes");
        btnIrClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrClientes.setContentAreaFilled(false);
        btnIrClientes.setFocusPainted(false);
        btnIrClientes.setOpaque(true);
        btnIrClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                irCadastroCliente(evt);
            }
        });

        javax.swing.GroupLayout painelSeçõesLayout = new javax.swing.GroupLayout(painelSeções);
        painelSeções.setLayout(painelSeçõesLayout);
        painelSeçõesLayout.setHorizontalGroup(
            painelSeçõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSeçõesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIrOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnIrEquipamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnIrTecnicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnIrClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelSeçõesLayout.setVerticalGroup(
            painelSeçõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSeçõesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(painelSeçõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIrOS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIrEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIrTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIrClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        painelCRUD.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 40, 40)), "O que deseja fazer?", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnIrCadastroOS.setBackground(new java.awt.Color(204, 0, 0));
        btnIrCadastroOS.setForeground(new java.awt.Color(255, 255, 255));
        btnIrCadastroOS.setText("Consultar uma OS");
        btnIrCadastroOS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrCadastroOS.setContentAreaFilled(false);
        btnIrCadastroOS.setFocusPainted(false);
        btnIrCadastroOS.setOpaque(true);
        btnIrCadastroOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                irConsultaOS(evt);
            }
        });

        btnIrCadastroOS1.setBackground(new java.awt.Color(100, 0, 0));
        btnIrCadastroOS1.setForeground(new java.awt.Color(255, 255, 255));
        btnIrCadastroOS1.setText("Cadastrar uma OS");
        btnIrCadastroOS1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 0, 0)));
        btnIrCadastroOS1.setBorderPainted(false);
        btnIrCadastroOS1.setContentAreaFilled(false);
        btnIrCadastroOS1.setFocusPainted(false);
        btnIrCadastroOS1.setOpaque(true);

        txtNomeColab.setText("aaaaaaaaa");

        javax.swing.GroupLayout painelCRUDLayout = new javax.swing.GroupLayout(painelCRUD);
        painelCRUD.setLayout(painelCRUDLayout);
        painelCRUDLayout.setHorizontalGroup(
            painelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCRUDLayout.createSequentialGroup()
                .addGroup(painelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCRUDLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(painelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIrCadastroOS1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIrCadastroOS, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCRUDLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtNomeColab)))
                .addGap(10, 10, 10))
        );
        painelCRUDLayout.setVerticalGroup(
            painelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCRUDLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnIrCadastroOS1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnIrCadastroOS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(txtNomeColab)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelDeRolagem.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 40, 40), 1, true), "Formulário de cadastro de OS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        painelDeRolagem.setToolTipText("");

        titleNumeroOS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleNumeroOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleNumeroOS.setText("N° da OS: ");

        txtNumeroOS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumeroOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNumeroOS.setText("00002020");

        checkClienteJaCadastrado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkClienteJaCadastrado.setText("Cliente já cadastado");
        checkClienteJaCadastrado.setFocusPainted(false);
        checkClienteJaCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkClienteJaCadastradoActionPerformed(evt);
            }
        });

        titleCpfOuCnpj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleCpfOuCnpj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCpfOuCnpj.setText("CPF ou CNPJ do cliente:");

        titleNomeOuRazao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleNomeOuRazao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleNomeOuRazao.setText("Nome/razao social:");

        campoCpfOuCnpj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoCpfOuCnpj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoCpfOuCnpj.setToolTipText("");
        campoCpfOuCnpj.setName("campoCpfOuCnpj"); // NOI18N
        campoCpfOuCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teclada(evt);
            }
        });

        campoNomeOuRazao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoNomeOuRazao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoNomeOuRazao.setName("campoNomeOuRazao"); // NOI18N

        titleSobrenomeOuFantasia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleSobrenomeOuFantasia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSobrenomeOuFantasia.setText("Sobronome/nome fantasia:");

        titleRgOuIe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleRgOuIe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleRgOuIe.setText("RG/IE:");

        campoRgOuIe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoRgOuIe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoRgOuIe.setName("campoRgOuIe"); // NOI18N

        campoSobrenomeOuFantasia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoSobrenomeOuFantasia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoSobrenomeOuFantasia.setName("campoSobrenomeOuFantasia"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 40, 40)), "Contato", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        titleEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEmail.setText("Email do cliente:");

        campoEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titleNumTel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleNumTel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleNumTel1.setText("Número de telefone principal:");

        campoNumTel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoNumTel1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titleNumTel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleNumTel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleNumTel2.setText("Número de telefone alternativo:");

        campoNumTel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoNumTel2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(titleEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleNumTel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleNumTel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoNumTel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNumTel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleEmail)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleNumTel1)
                    .addComponent(campoNumTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleNumTel2)
                    .addComponent(campoNumTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 40, 40)), "Endereço", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        titleEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEstado.setText("Estado:");

        titleCep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleCep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCep.setText("CEP:");

        campoCep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoCep.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titleCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleCidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCidade.setText("Cidade:");

        campoCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoCidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        caixaCombinacaoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        caixaCombinacaoEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 40, 40)));
        caixaCombinacaoEstado.setFocusable(false);

        titleBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleBairro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleBairro.setText("Bairro:");

        campoBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoBairro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titleLograd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleLograd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLograd.setText("Logradouro:");

        campoLograd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoLograd.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titleLogradNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleLogradNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLogradNum.setText("N°:");

        campoLogradNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoLogradNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titleLogradComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleLogradComp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLogradComp.setText("Complemento:");

        campoLogradComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoLogradComp.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(titleLograd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoLograd))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(titleEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(caixaCombinacaoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(titleCep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoCep, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(titleCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(titleBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(titleLogradNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoLogradNum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleLogradComp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoLogradComp, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleEstado)
                    .addComponent(caixaCombinacaoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleCep)
                    .addComponent(campoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleCidade)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleBairro)
                    .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLograd)
                    .addComponent(campoLograd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titleLogradComp)
                        .addComponent(campoLogradComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titleLogradNum)
                        .addComponent(campoLogradNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 40, 40)), "Equipamento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        titleEquipTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleEquipTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEquipTipo.setText("Tipo:");

        campoEquipTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoEquipTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titleEquipMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleEquipMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEquipMarca.setText("Marca:");

        campoEquipMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoEquipMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titleEquipModelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleEquipModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEquipModelo.setText("Modelo:");

        campoEquipModelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoEquipModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titleEquipNsOuImei.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleEquipNsOuImei.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEquipNsOuImei.setText("N/S ou IMEI:");

        campoEquipNsOuImei.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoEquipNsOuImei.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titleEquipAcessorios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleEquipAcessorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEquipAcessorios.setText("Acessórios:");

        titleEquipDefeitoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleEquipDefeitoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEquipDefeitoCliente.setText("Defeito reclamado pelo cliente:");
        titleEquipDefeitoCliente.setToolTipText("");

        campoEquipAcessorios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoEquipAcessorios.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campoEquipDefeitoCliente.setColumns(20);
        campoEquipDefeitoCliente.setRows(5);
        jScrollPane5.setViewportView(campoEquipDefeitoCliente);

        campoEquipObservacoes.setColumns(20);
        campoEquipObservacoes.setRows(5);
        jScrollPane6.setViewportView(campoEquipObservacoes);

        titleEquipObservacoes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleEquipObservacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEquipObservacoes.setText("Observações:");
        titleEquipObservacoes.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(titleEquipTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoEquipTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(titleEquipModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoEquipModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(titleEquipMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoEquipMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(117, 117, 117))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleEquipNsOuImei)
                            .addComponent(titleEquipAcessorios))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEquipNsOuImei)
                            .addComponent(campoEquipAcessorios, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleEquipDefeitoCliente)
                            .addComponent(titleEquipObservacoes))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleEquipTipo)
                    .addComponent(campoEquipTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleEquipMarca)
                    .addComponent(campoEquipMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleEquipModelo)
                    .addComponent(campoEquipModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleEquipNsOuImei)
                    .addComponent(campoEquipNsOuImei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleEquipAcessorios)
                    .addComponent(campoEquipAcessorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(titleEquipDefeitoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleEquipObservacoes)
                .addGap(10, 10, 10))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(302, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        titlePrevisaoSaida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titlePrevisaoSaida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlePrevisaoSaida.setText("Previsão de saída:");

        btnCadastrar.setBackground(new java.awt.Color(204, 0, 0));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnCadastrar.setContentAreaFilled(false);
        btnCadastrar.setFocusPainted(false);
        btnCadastrar.setName("btnCadastrar"); // NOI18N
        btnCadastrar.setOpaque(true);
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarDados(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPressionado(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSolto(evt);
            }
        });

        btnLimparCampos.setBackground(new java.awt.Color(204, 0, 0));
        btnLimparCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimparCampos.setText("Limpar campos");
        btnLimparCampos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnLimparCampos.setContentAreaFilled(false);
        btnLimparCampos.setFocusPainted(false);
        btnLimparCampos.setName("btnLimparCampos"); // NOI18N
        btnLimparCampos.setOpaque(true);
        btnLimparCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limparDados(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPressionado(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSolto(evt);
            }
        });

        campoPrevisaoSaida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        titleOrcamentoAtual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleOrcamentoAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleOrcamentoAtual.setText("Orçamento atual:");

        campoOrcamentoAtual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout painelDoFormularioLayout = new javax.swing.GroupLayout(painelDoFormulario);
        painelDoFormulario.setLayout(painelDoFormularioLayout);
        painelDoFormularioLayout.setHorizontalGroup(
            painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDoFormularioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(painelDoFormularioLayout.createSequentialGroup()
                            .addComponent(titleSobrenomeOuFantasia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campoSobrenomeOuFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDoFormularioLayout.createSequentialGroup()
                            .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(titleNomeOuRazao)
                                .addComponent(titleRgOuIe)
                                .addComponent(titleCpfOuCnpj))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoNomeOuRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCpfOuCnpj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoRgOuIe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(painelDoFormularioLayout.createSequentialGroup()
                        .addComponent(titleNumeroOS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroOS, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkClienteJaCadastrado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDoFormularioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelDoFormularioLayout.createSequentialGroup()
                        .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelDoFormularioLayout.createSequentialGroup()
                                .addComponent(titlePrevisaoSaida)
                                .addGap(18, 18, 18)
                                .addComponent(campoPrevisaoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titleOrcamentoAtual)
                                .addGap(18, 18, 18)
                                .addComponent(campoOrcamentoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDoFormularioLayout.createSequentialGroup()
                                .addComponent(btnLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)))
                .addGap(19, 19, 19))
        );
        painelDoFormularioLayout.setVerticalGroup(
            painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDoFormularioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleNumeroOS)
                    .addComponent(txtNumeroOS)
                    .addComponent(checkClienteJaCadastrado))
                .addGap(20, 20, 20)
                .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleCpfOuCnpj)
                    .addComponent(campoCpfOuCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleRgOuIe)
                    .addComponent(campoRgOuIe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleNomeOuRazao)
                    .addComponent(campoNomeOuRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleSobrenomeOuFantasia)
                    .addComponent(campoSobrenomeOuFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlePrevisaoSaida)
                    .addComponent(campoPrevisaoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleOrcamentoAtual)
                    .addComponent(campoOrcamentoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelDoFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        txtErroEquipPrevisaoSaida.setForeground(new java.awt.Color(240, 240, 240));
        txtErroEquipPrevisaoSaida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroEquipPrevisaoSaida.setText("jLabel1");

        txtErroLogradNum.setForeground(new java.awt.Color(240, 240, 240));
        txtErroLogradNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroLogradNum.setText("jLabel1");

        txtErroEstado.setForeground(new java.awt.Color(240, 240, 240));
        txtErroEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroEstado.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtErroLogradNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtErroEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(txtErroEquipPrevisaoSaida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(txtErroEstado)
                .addGap(110, 110, 110)
                .addComponent(txtErroLogradNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtErroEquipPrevisaoSaida)
                .addGap(181, 181, 181))
        );

        txtErroEquipOrcamento.setForeground(new java.awt.Color(240, 240, 240));
        txtErroEquipOrcamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroEquipOrcamento.setText("jLabel1");

        txtErroEquipObservacoes.setForeground(new java.awt.Color(240, 240, 240));
        txtErroEquipObservacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroEquipObservacoes.setText("jLabel1");

        txtErroEquipDefeitoCliente.setForeground(new java.awt.Color(240, 240, 240));
        txtErroEquipDefeitoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroEquipDefeitoCliente.setText("jLabel1");

        txtErroEquipAcessorios.setForeground(new java.awt.Color(240, 240, 240));
        txtErroEquipAcessorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroEquipAcessorios.setText("jLabel1");

        txtErroEquipNsOuImei.setForeground(new java.awt.Color(240, 240, 240));
        txtErroEquipNsOuImei.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroEquipNsOuImei.setText("jLabel1");

        txtErroEquipModelo.setForeground(new java.awt.Color(240, 240, 240));
        txtErroEquipModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroEquipModelo.setText("jLabel1");

        txtErroEquipMarca.setForeground(new java.awt.Color(240, 240, 240));
        txtErroEquipMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroEquipMarca.setText("jLabel1");

        txtErroEquipTipo.setForeground(new java.awt.Color(240, 240, 240));
        txtErroEquipTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroEquipTipo.setText("jLabel1");

        txtErroLogradComp.setForeground(new java.awt.Color(240, 240, 240));
        txtErroLogradComp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroLogradComp.setText("jLabel1");

        txtErroLograd.setForeground(new java.awt.Color(240, 240, 240));
        txtErroLograd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroLograd.setText("jLabel1");

        txtErroBairro.setForeground(new java.awt.Color(240, 240, 240));
        txtErroBairro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroBairro.setText("jLabel1");

        txtErroCidade.setForeground(new java.awt.Color(240, 240, 240));
        txtErroCidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroCidade.setText("jLabel1");

        txtErroCep.setForeground(new java.awt.Color(240, 240, 240));
        txtErroCep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroCep.setText("jLabel1");

        txtErroNumTel2.setForeground(new java.awt.Color(240, 240, 240));
        txtErroNumTel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroNumTel2.setText("jLabel1");

        txtErroNumTel1.setForeground(new java.awt.Color(240, 240, 240));
        txtErroNumTel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroNumTel1.setText("jLabel1");

        txtErroEmail.setForeground(new java.awt.Color(240, 240, 240));
        txtErroEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroEmail.setText("jLabel1");

        txtErroSobrenomeOuFantasia.setForeground(new java.awt.Color(240, 240, 240));
        txtErroSobrenomeOuFantasia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroSobrenomeOuFantasia.setText("jLabel1");

        txtErroNomeOuRazao.setForeground(new java.awt.Color(240, 240, 240));
        txtErroNomeOuRazao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroNomeOuRazao.setText("jLabel1");

        txtErroRgOuIe.setForeground(new java.awt.Color(240, 240, 240));
        txtErroRgOuIe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroRgOuIe.setText("jLabel1");

        txtErroCpfOuCnpj.setForeground(new java.awt.Color(240, 240, 240));
        txtErroCpfOuCnpj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroCpfOuCnpj.setText("jLabel1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtErroEquipAcessorios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtErroEquipNsOuImei, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 58, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(txtErroRgOuIe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtErroCpfOuCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtErroNomeOuRazao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroSobrenomeOuFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroNumTel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroNumTel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroCep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroLograd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroLogradComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroEquipTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroEquipMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroEquipModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroEquipDefeitoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroEquipObservacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErroEquipOrcamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtErroRgOuIe)
                    .addComponent(txtErroCpfOuCnpj))
                .addGap(18, 18, 18)
                .addComponent(txtErroNomeOuRazao)
                .addGap(28, 28, 28)
                .addComponent(txtErroSobrenomeOuFantasia)
                .addGap(40, 40, 40)
                .addComponent(txtErroEmail)
                .addGap(18, 18, 18)
                .addComponent(txtErroNumTel1)
                .addGap(18, 18, 18)
                .addComponent(txtErroNumTel2)
                .addGap(42, 42, 42)
                .addComponent(txtErroCep)
                .addGap(18, 18, 18)
                .addComponent(txtErroCidade)
                .addGap(18, 18, 18)
                .addComponent(txtErroBairro)
                .addGap(18, 18, 18)
                .addComponent(txtErroLograd)
                .addGap(18, 18, 18)
                .addComponent(txtErroLogradComp)
                .addGap(47, 47, 47)
                .addComponent(txtErroEquipTipo)
                .addGap(18, 18, 18)
                .addComponent(txtErroEquipMarca)
                .addGap(18, 18, 18)
                .addComponent(txtErroEquipModelo)
                .addGap(18, 18, 18)
                .addComponent(txtErroEquipNsOuImei)
                .addGap(18, 18, 18)
                .addComponent(txtErroEquipAcessorios)
                .addGap(79, 79, 79)
                .addComponent(txtErroEquipDefeitoCliente)
                .addGap(111, 111, 111)
                .addComponent(txtErroEquipObservacoes)
                .addGap(76, 76, 76)
                .addComponent(txtErroEquipOrcamento)
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout painelDoScrollLayout = new javax.swing.GroupLayout(painelDoScroll);
        painelDoScroll.setLayout(painelDoScrollLayout);
        painelDoScrollLayout.setHorizontalGroup(
            painelDoScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDoScrollLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDoFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        painelDoScrollLayout.setVerticalGroup(
            painelDoScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelDoScrollLayout.createSequentialGroup()
                .addGroup(painelDoScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDoScrollLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(painelDoFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        painelDeRolagem.setViewportView(painelDoScroll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelSeções, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(painelDeRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(painelSeções, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelCRUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDeRolagem))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void irConsultaOS(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irConsultaOS
        u.irDePara(this, C_OS_TELA.getRUD_OS());
    }//GEN-LAST:event_irConsultaOS

    private void irCadastroOS(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irCadastroOS
        u.irDePara(this, C_OS_TELA.getC_OS());
    }//GEN-LAST:event_irCadastroOS

    private void irCadastroEquip(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irCadastroEquip
//        u.irDePara(this, C_OS_TELA.getC_EQUIP());
    }//GEN-LAST:event_irCadastroEquip

    private void irCadastroTec(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irCadastroTec
        // u.irDePara(this, C_OS_TELA.getC_TEC());
    }//GEN-LAST:event_irCadastroTec

    private void irCadastroCliente(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irCadastroCliente
        // u.irDePara(this, C_OS_TELA.getC_CLIENTE());
    }//GEN-LAST:event_irCadastroCliente

    private void checkClienteJaCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkClienteJaCadastradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkClienteJaCadastradoActionPerformed

    private void cadastrarDados(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarDados
        /*
            MÉTODO RESPONSÁVEL POR CADASTRAR OS DADOS DO CLIENTE
        */
        btnClicado(evt);
        
        Cliente cliente = new Cliente();
        cliente.setClienteCpfOuCnpj(campoCpfOuCnpj.getText());
        cliente.setClienteRgOuIe(campoRgOuIe.getText());       
        cliente.setClienteNomeOuRazao(campoNomeOuRazao.getText());
        cliente.setClienteSobrenomeOuFantasia(campoSobrenomeOuFantasia.getText());
        if (campoCpfOuCnpj.getText().length() > 14){
            cliente.setClientePj(true);
        } else {
            cliente.setClientePj(false);
        }
        cliente.setClienteEndEstado(caixaCombinacaoEstado.getSelectedItem().toString());
        cliente.setClienteEndCep(campoCep.getText());
        cliente.setClienteEndCidade(campoCidade.getText());
        cliente.setClienteEndBairro(campoBairro.getText());
        cliente.setClienteEndLograd(campoLograd.getText());
        cliente.setClienteEndLogradNum(campoLogradNum.getText());
        cliente.setClienteEndLogradComp(campoLogradComp.getText());
        
        Contato contato = new Contato();
        contato.setClienteContatoEmail(campoEmail.getText());
        contato.setClienteContatoNumTel1(campoNumTel1.getText());
        contato.setClienteContatoNumTel2(campoNumTel2.getText());
        
        OS os = new OS();
        os.setOsPrevisaoSaida(campoPrevisaoSaida.getText());
        os.setOsOrcamentoAtual(campoOrcamentoAtual.getText());
      
        Equipamento equip = new Equipamento();
        equip.setEquipTipo(campoEquipTipo.getText());
        equip.setEquipMarca(campoEquipMarca.getText());
        equip.setEquipModelo(campoEquipModelo.getText());
        equip.setEquipNsOuImei(campoEquipNsOuImei.getText());
        equip.setEquipAcessorios(campoEquipAcessorios.getText());
        equip.setEquipDefeitoCliente(campoEquipDefeitoCliente.getText());
        equip.setEquipObservacoes(campoEquipObservacoes.getText());
        
        Colab colab = new Colab();
        colab.setColabNome(txtNomeColab.getText());
        
        CadastroDAO cadastrar = new CadastroDAO();
        cadastrar.cadastrarDados(cliente, contato, equip, os, colab);
    }//GEN-LAST:event_cadastrarDados

    private void btnPressionado(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPressionado
        /*
            MÉTODO RESPONSÁVEL POR MUDAR A COR DO BOTAO QUANDO FOR PRESSSIONADO
        */
        //pega o botao que foi pressionado e muda a cor
        evt.getComponent().setBackground(new Color(100,0,0));
    }//GEN-LAST:event_btnPressionado

    private void btnSolto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolto
        /*
            MÉTODO RESPONSÁVEL POR MUDAR A COR DO BOTAO QUANDO FOR SOLTO   
        */
        //pega o botao que foi solto e muda a cor
        evt.getComponent().setBackground(new Color(204,0,0));
    }//GEN-LAST:event_btnSolto

    private void limparDados(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparDados
        /*
            BTN QUE LIMPA OS DADOS
        */
        btnClicado(evt);
        limparCampos();
    }//GEN-LAST:event_limparDados

    private void teclada(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teclada
        /*
            SERVE PARA AS VERIFICAÇÕES E FORMATAÇÕES DE STRINGS
        */
        
        if ("\b".equals(Character.toString(evt.getKeyChar()))){
            campoCpfOuCnpj.setText(fs.apagar(campoCpfOuCnpj.getText(), evt.getComponent().getName()));
        }
        if (vs.cpfOuCnpj(evt, campoCpfOuCnpj.getText()) == ""){
            txtErroCpfOuCnpj.setForeground(new Color(240,240,240));           
        } else {
            txtErroCpfOuCnpj.setText(vs.cpfOuCnpj(evt, campoCpfOuCnpj.getText()));
            txtErroCpfOuCnpj.setForeground(new Color(255,0,0));
        }              
        String txt = fs.cpfOuCnpj(evt, campoCpfOuCnpj.getText());
        campoCpfOuCnpj.setText(txt);   
    }//GEN-LAST:event_teclada

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_OS_TELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_OS_TELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_OS_TELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_OS_TELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                getC_OS().setVisible(true);
            }
        });       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnIrCadastroOS;
    private javax.swing.JButton btnIrCadastroOS1;
    private javax.swing.JButton btnIrClientes;
    private javax.swing.JButton btnIrEquipamentos;
    private javax.swing.JButton btnIrOS;
    private javax.swing.JButton btnIrTecnicos;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JComboBox<String> caixaCombinacaoEstado;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCep;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoCpfOuCnpj;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEquipAcessorios;
    private javax.swing.JTextArea campoEquipDefeitoCliente;
    private javax.swing.JTextField campoEquipMarca;
    private javax.swing.JTextField campoEquipModelo;
    private javax.swing.JTextField campoEquipNsOuImei;
    private javax.swing.JTextArea campoEquipObservacoes;
    private javax.swing.JTextField campoEquipTipo;
    private javax.swing.JTextField campoLograd;
    private javax.swing.JTextField campoLogradComp;
    private javax.swing.JTextField campoLogradNum;
    private javax.swing.JTextField campoNomeOuRazao;
    private javax.swing.JTextField campoNumTel1;
    private javax.swing.JTextField campoNumTel2;
    private javax.swing.JTextField campoOrcamentoAtual;
    private javax.swing.JTextField campoPrevisaoSaida;
    private javax.swing.JTextField campoRgOuIe;
    private javax.swing.JTextField campoSobrenomeOuFantasia;
    private javax.swing.JCheckBox checkClienteJaCadastrado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel painelCRUD;
    private javax.swing.JScrollPane painelDeRolagem;
    private javax.swing.JPanel painelDoFormulario;
    private javax.swing.JPanel painelDoScroll;
    private javax.swing.JPanel painelSeções;
    private javax.swing.JLabel titleBairro;
    private javax.swing.JLabel titleCep;
    private javax.swing.JLabel titleCidade;
    private javax.swing.JLabel titleCpfOuCnpj;
    private javax.swing.JLabel titleEmail;
    private javax.swing.JLabel titleEquipAcessorios;
    private javax.swing.JLabel titleEquipDefeitoCliente;
    private javax.swing.JLabel titleEquipMarca;
    private javax.swing.JLabel titleEquipModelo;
    private javax.swing.JLabel titleEquipNsOuImei;
    private javax.swing.JLabel titleEquipObservacoes;
    private javax.swing.JLabel titleEquipTipo;
    private javax.swing.JLabel titleEstado;
    private javax.swing.JLabel titleLograd;
    private javax.swing.JLabel titleLogradComp;
    private javax.swing.JLabel titleLogradNum;
    private javax.swing.JLabel titleNomeOuRazao;
    private javax.swing.JLabel titleNumTel1;
    private javax.swing.JLabel titleNumTel2;
    private javax.swing.JLabel titleNumeroOS;
    private javax.swing.JLabel titleOrcamentoAtual;
    private javax.swing.JLabel titlePrevisaoSaida;
    private javax.swing.JLabel titleRgOuIe;
    private javax.swing.JLabel titleSobrenomeOuFantasia;
    private javax.swing.JLabel txtErroBairro;
    private javax.swing.JLabel txtErroCep;
    private javax.swing.JLabel txtErroCidade;
    private javax.swing.JLabel txtErroCpfOuCnpj;
    private javax.swing.JLabel txtErroEmail;
    private javax.swing.JLabel txtErroEquipAcessorios;
    private javax.swing.JLabel txtErroEquipDefeitoCliente;
    private javax.swing.JLabel txtErroEquipMarca;
    private javax.swing.JLabel txtErroEquipModelo;
    private javax.swing.JLabel txtErroEquipNsOuImei;
    private javax.swing.JLabel txtErroEquipObservacoes;
    private javax.swing.JLabel txtErroEquipOrcamento;
    private javax.swing.JLabel txtErroEquipPrevisaoSaida;
    private javax.swing.JLabel txtErroEquipTipo;
    private javax.swing.JLabel txtErroEstado;
    private javax.swing.JLabel txtErroLograd;
    private javax.swing.JLabel txtErroLogradComp;
    private javax.swing.JLabel txtErroLogradNum;
    private javax.swing.JLabel txtErroNomeOuRazao;
    private javax.swing.JLabel txtErroNumTel1;
    private javax.swing.JLabel txtErroNumTel2;
    private javax.swing.JLabel txtErroRgOuIe;
    private javax.swing.JLabel txtErroSobrenomeOuFantasia;
    private javax.swing.JLabel txtNomeColab;
    private javax.swing.JLabel txtNumeroOS;
    // End of variables declaration//GEN-END:variables
   
    private void limparCampos(){
        /*
            MÉTODO REPSONSÁVEL POR LIMPAR OS CAMPOS
        */
        checkClienteJaCadastrado.setSelected(false);
        campoCpfOuCnpj.setText("");
        campoRgOuIe.setText("");        
        campoNomeOuRazao.setText("");
        campoSobrenomeOuFantasia.setText("");
        campoEmail.setText("");
        campoNumTel1.setText("");
        campoNumTel2.setText("");
        caixaCombinacaoEstado.setSelectedIndex(0);
        campoCep.setText("");
        campoCidade.setText("");
        campoBairro.setText("");
        campoLograd.setText("");
        campoLogradNum.setText("");
        campoLogradComp.setText("");
        campoEquipTipo.setText("");
        campoEquipMarca.setText("");
        campoEquipModelo.setText("");
        campoEquipNsOuImei.setText("");
        campoEquipAcessorios.setText("");
        campoEquipDefeitoCliente.setText("");
        campoPrevisaoSaida.setText("");
        campoEquipObservacoes.setText("");
        campoOrcamentoAtual.setText("");
    }
    
    private void btnClicado(java.awt.event.MouseEvent evt){
        /*
            MÉTODO RESPONSÁVEL POR MUDAR A COR DE FUNDO DO BOTAO QUANDO FOR CLICADO
        */
        //muda a cor de fundo
        evt.getComponent().setBackground(new Color(100,0,0));
        //apos algum tempo, retorna a cor de fundo que tava
        new Timer().schedule(
            new TimerTask(){
                @Override
                public void run(){
                    evt.getComponent().setBackground(new Color(204,0,0));
                }
        }, 50);
    }

}