/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pif.desktop.TELAS;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import pif.desktop.Classes.FormatacaoStrings;
import pif.desktop.Classes.OS;
import pif.desktop.Classes.Orcamento;
import pif.desktop.Classes.VerificacaoStrings;
import pif.desktop.DAO.OrcamentoDAO;
import pif.desktop.DAO.OsDAO;

/**
 *
 * @author arthu
 */
public class RELATORIO_TELA extends javax.swing.JFrame {

    TelaUtils u = new TelaUtils();
    boolean rudAberto;
    Image icon;
    FormatacaoStrings fs = new FormatacaoStrings();
    VerificacaoStrings vs = new VerificacaoStrings();

    /**
     * Creates new form RELATORIO_TELA
     */
    public RELATORIO_TELA() {
        try {
            icon = ImageIO.read(getClass().getResource("/resources/icon.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        this.setIconImage(icon);
        this.setTitle("Relatórios da oficina");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        painelSecoes = new javax.swing.JPanel();
        btnIrOS = new javax.swing.JButton();
        btnIrUsuario = new javax.swing.JButton();
        painelCRUD = new javax.swing.JPanel();
        painelOpcoesCRUD = new javax.swing.JPanel();
        btnIrRelatorios = new javax.swing.JButton();
        btnIrCadastroOS = new javax.swing.JButton();
        btnIrConsultaOS = new javax.swing.JButton();
        painelFormularioConsulta = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        campoData1Os = new javax.swing.JTextField();
        campoData2Os = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnIrCadastroOS4 = new javax.swing.JButton();
        btnIrCadastroOS9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnIrCadastroOS1 = new javax.swing.JButton();
        txtErroOs = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        campoData1Faturamento = new javax.swing.JTextField();
        campoData2Faturamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnIrCadastroOS5 = new javax.swing.JButton();
        btnIrCadastroOS6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnIrCadastroOS7 = new javax.swing.JButton();
        btnIrCadastroOS8 = new javax.swing.JButton();
        txtErroFaturamento = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1368, 768));
        setPreferredSize(new java.awt.Dimension(1368, 768));

        painelSecoes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 40, 40)), "Para qual seção deseja ir?", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnIrOS.setBackground(new java.awt.Color(100, 0, 0));
        btnIrOS.setForeground(new java.awt.Color(255, 255, 255));
        btnIrOS.setText("Ordem de serviço");
        btnIrOS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 0, 0)));
        btnIrOS.setContentAreaFilled(false);
        btnIrOS.setFocusPainted(false);
        btnIrOS.setOpaque(true);
        btnIrOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIrOSirCadastroOS(evt);
            }
        });

        btnIrUsuario.setBackground(new java.awt.Color(204, 0, 0));
        btnIrUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnIrUsuario.setText("Suas informações");
        btnIrUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrUsuario.setContentAreaFilled(false);
        btnIrUsuario.setFocusPainted(false);
        btnIrUsuario.setOpaque(true);
        btnIrUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIrUsuarioirInfoUser(evt);
            }
        });

        javax.swing.GroupLayout painelSecoesLayout = new javax.swing.GroupLayout(painelSecoes);
        painelSecoes.setLayout(painelSecoesLayout);
        painelSecoesLayout.setHorizontalGroup(
            painelSecoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSecoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIrOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btnIrUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelSecoesLayout.setVerticalGroup(
            painelSecoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSecoesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(painelSecoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIrOS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIrUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        painelCRUD.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 40, 40)), "O que deseja fazer?", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnIrRelatorios.setBackground(new java.awt.Color(100, 0, 0));
        btnIrRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        btnIrRelatorios.setText("Consultar relatórios");
        btnIrRelatorios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 0, 0)));
        btnIrRelatorios.setBorderPainted(false);
        btnIrRelatorios.setContentAreaFilled(false);
        btnIrRelatorios.setFocusPainted(false);
        btnIrRelatorios.setOpaque(true);

        btnIrCadastroOS.setBackground(new java.awt.Color(204, 0, 0));
        btnIrCadastroOS.setForeground(new java.awt.Color(255, 255, 255));
        btnIrCadastroOS.setText("Cadastrar uma OS");
        btnIrCadastroOS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrCadastroOS.setContentAreaFilled(false);
        btnIrCadastroOS.setFocusPainted(false);
        btnIrCadastroOS.setOpaque(true);
        btnIrCadastroOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                irCadastroOS(evt);
            }
        });

        btnIrConsultaOS.setBackground(new java.awt.Color(204, 0, 0));
        btnIrConsultaOS.setForeground(new java.awt.Color(255, 255, 255));
        btnIrConsultaOS.setText("Consultar uma OS");
        btnIrConsultaOS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrConsultaOS.setContentAreaFilled(false);
        btnIrConsultaOS.setFocusPainted(false);
        btnIrConsultaOS.setOpaque(true);
        btnIrConsultaOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                irConsultaOS(evt);
            }
        });

        javax.swing.GroupLayout painelOpcoesCRUDLayout = new javax.swing.GroupLayout(painelOpcoesCRUD);
        painelOpcoesCRUD.setLayout(painelOpcoesCRUDLayout);
        painelOpcoesCRUDLayout.setHorizontalGroup(
            painelOpcoesCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOpcoesCRUDLayout.createSequentialGroup()
                .addGroup(painelOpcoesCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelOpcoesCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelOpcoesCRUDLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnIrCadastroOS, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelOpcoesCRUDLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnIrRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnIrConsultaOS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        painelOpcoesCRUDLayout.setVerticalGroup(
            painelOpcoesCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelOpcoesCRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIrCadastroOS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIrConsultaOS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIrRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout painelCRUDLayout = new javax.swing.GroupLayout(painelCRUD);
        painelCRUD.setLayout(painelCRUDLayout);
        painelCRUDLayout.setHorizontalGroup(
            painelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelOpcoesCRUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelCRUDLayout.setVerticalGroup(
            painelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCRUDLayout.createSequentialGroup()
                .addComponent(painelOpcoesCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 512, Short.MAX_VALUE))
        );

        painelFormularioConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 35, 35)), "Relatórios ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 40, 0)), "Ver ORDENS DE SERVIÇO entre...", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        campoData1Os.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoData1Os.setName("1"); // NOI18N
        campoData1Os.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tecladaDataOs(evt);
            }
        });

        campoData2Os.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoData2Os.setName("2"); // NOI18N
        campoData2Os.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tecladaDataOs(evt);
            }
        });

        jLabel1.setText("e");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 40, 0)), "Ver relatório diário", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        btnIrCadastroOS4.setBackground(new java.awt.Color(204, 0, 0));
        btnIrCadastroOS4.setForeground(new java.awt.Color(255, 255, 255));
        btnIrCadastroOS4.setText("Gráfico em barras de quantos SAÍRAM");
        btnIrCadastroOS4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrCadastroOS4.setContentAreaFilled(false);
        btnIrCadastroOS4.setFocusPainted(false);
        btnIrCadastroOS4.setOpaque(true);
        btnIrCadastroOS4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirGraficoBarraSaida(evt);
            }
        });

        btnIrCadastroOS9.setBackground(new java.awt.Color(204, 0, 0));
        btnIrCadastroOS9.setForeground(new java.awt.Color(255, 255, 255));
        btnIrCadastroOS9.setText("Gráfico em barras de quantos ENTRARAM");
        btnIrCadastroOS9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrCadastroOS9.setContentAreaFilled(false);
        btnIrCadastroOS9.setFocusPainted(false);
        btnIrCadastroOS9.setOpaque(true);
        btnIrCadastroOS9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirGraficoBarraEntrada(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIrCadastroOS4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIrCadastroOS9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(btnIrCadastroOS4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIrCadastroOS9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 40, 0)), "Ver relatório total", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        btnIrCadastroOS1.setBackground(new java.awt.Color(204, 0, 0));
        btnIrCadastroOS1.setForeground(new java.awt.Color(255, 255, 255));
        btnIrCadastroOS1.setText("Gráfico em pizza");
        btnIrCadastroOS1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrCadastroOS1.setContentAreaFilled(false);
        btnIrCadastroOS1.setFocusPainted(false);
        btnIrCadastroOS1.setOpaque(true);
        btnIrCadastroOS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirGraficoPizzaOs(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIrCadastroOS1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnIrCadastroOS1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtErroOs.setForeground(new java.awt.Color(240, 240, 240));
        txtErroOs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroOs.setText("txtErro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(campoData1Os, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campoData2Os, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtErroOs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoData1Os, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoData2Os, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtErroOs))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 40, 0)), "Ver FATURAMENTO entre...", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        campoData1Faturamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoData1Faturamento.setName("1"); // NOI18N
        campoData1Faturamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tecladaDataFaturamento(evt);
            }
        });

        campoData2Faturamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoData2Faturamento.setName("2"); // NOI18N
        campoData2Faturamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tecladaDataFaturamento(evt);
            }
        });

        jLabel2.setText("e");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 40, 0)), "Ver relatório diário", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        btnIrCadastroOS5.setBackground(new java.awt.Color(204, 0, 0));
        btnIrCadastroOS5.setForeground(new java.awt.Color(255, 255, 255));
        btnIrCadastroOS5.setText("Gráfico em pizza");
        btnIrCadastroOS5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrCadastroOS5.setContentAreaFilled(false);
        btnIrCadastroOS5.setFocusPainted(false);
        btnIrCadastroOS5.setOpaque(true);
        btnIrCadastroOS5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirGraficoPizzaFaturamentoDiario(evt);
            }
        });

        btnIrCadastroOS6.setBackground(new java.awt.Color(204, 0, 0));
        btnIrCadastroOS6.setForeground(new java.awt.Color(255, 255, 255));
        btnIrCadastroOS6.setText("Gráfico em barras");
        btnIrCadastroOS6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrCadastroOS6.setContentAreaFilled(false);
        btnIrCadastroOS6.setFocusPainted(false);
        btnIrCadastroOS6.setOpaque(true);
        btnIrCadastroOS6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirGraficoBarraFaturamentoDiario(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIrCadastroOS5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIrCadastroOS6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(btnIrCadastroOS6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnIrCadastroOS5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 40, 0)), "Ver relatório total", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        btnIrCadastroOS7.setBackground(new java.awt.Color(204, 0, 0));
        btnIrCadastroOS7.setForeground(new java.awt.Color(255, 255, 255));
        btnIrCadastroOS7.setText("Gráfico em pizza");
        btnIrCadastroOS7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrCadastroOS7.setContentAreaFilled(false);
        btnIrCadastroOS7.setFocusPainted(false);
        btnIrCadastroOS7.setOpaque(true);
        btnIrCadastroOS7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirGraficoPizzaFaturamentoTotal(evt);
            }
        });

        btnIrCadastroOS8.setBackground(new java.awt.Color(204, 0, 0));
        btnIrCadastroOS8.setForeground(new java.awt.Color(255, 255, 255));
        btnIrCadastroOS8.setText("Gráfico em barras");
        btnIrCadastroOS8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrCadastroOS8.setContentAreaFilled(false);
        btnIrCadastroOS8.setFocusPainted(false);
        btnIrCadastroOS8.setOpaque(true);
        btnIrCadastroOS8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirGraficoBarraFaturamentoTotal(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIrCadastroOS7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIrCadastroOS8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(btnIrCadastroOS8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnIrCadastroOS7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtErroFaturamento.setForeground(new java.awt.Color(240, 240, 240));
        txtErroFaturamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErroFaturamento.setText("txtErro");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoData1Faturamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(campoData2Faturamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtErroFaturamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoData1Faturamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoData2Faturamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtErroFaturamento))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelFormularioConsultaLayout = new javax.swing.GroupLayout(painelFormularioConsulta);
        painelFormularioConsulta.setLayout(painelFormularioConsultaLayout);
        painelFormularioConsultaLayout.setHorizontalGroup(
            painelFormularioConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFormularioConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelFormularioConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelFormularioConsultaLayout.setVerticalGroup(
            painelFormularioConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFormularioConsultaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelSecoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelFormularioConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(painelSecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelCRUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelFormularioConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrOSirCadastroOS(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIrOSirCadastroOS
        u.irDePara(this, C_OS_TELA.getC_OS());
    }//GEN-LAST:event_btnIrOSirCadastroOS

    private void btnIrUsuarioirInfoUser(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIrUsuarioirInfoUser
        u.irDePara(this, C_OS_TELA.getUSER_TELA());
    }//GEN-LAST:event_btnIrUsuarioirInfoUser

    private void irConsultaOS(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irConsultaOS
        u.irDePara(this, C_OS_TELA.getRUD_OS());
    }//GEN-LAST:event_irConsultaOS

    private void irCadastroOS(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irCadastroOS
        u.irDePara(this, C_OS_TELA.getC_OS());
    }//GEN-LAST:event_irCadastroOS

    private void abrirGraficoPizzaFaturamentoDiario(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirGraficoPizzaFaturamentoDiario
        JFrame jfPizaa = new JFrame();
        DefaultPieDataset pizza = new DefaultPieDataset();
        OrcamentoDAO orcdao = new OrcamentoDAO();
        List<Orcamento> orcs = new ArrayList<>();
        orcs = orcdao.consultarVendasDiarias(fs.retirarFormatacaoData(campoData1Faturamento.getText()), fs.retirarFormatacaoData(campoData2Faturamento.getText()));
        for (int i = 0; i < orcs.size(); i++) {
            pizza.setValue(orcs.get(i).getOrcamento_data(), Double.parseDouble(orcs.get(i).getOrcamento_preco_pecas()) + Double.parseDouble(orcs.get(i).getOrcamento_preco_servicos()));
        }
        JFreeChart graficoPizza = ChartFactory.createPieChart("Faturamento entre " + campoData1Faturamento.getText() + " e " + campoData2Faturamento.getText(), pizza, true, true, false);
        ChartPanel painelzadaP = new ChartPanel(graficoPizza);
        jfPizaa.setIconImage(icon);
        jfPizaa.setTitle("Faturamento diário");
        jfPizaa.add(painelzadaP);
        jfPizaa.setSize(950, 700);
        jfPizaa.setLocationRelativeTo(null);
        jfPizaa.setVisible(true);
    }//GEN-LAST:event_abrirGraficoPizzaFaturamentoDiario

    private void abrirGraficoBarraFaturamentoDiario(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirGraficoBarraFaturamentoDiario
        JFrame jfBarra = new JFrame();
        DefaultCategoryDataset barra = new DefaultCategoryDataset();
        OrcamentoDAO orcdao = new OrcamentoDAO();
        List<Orcamento> orcs = new ArrayList<>();
        orcs = orcdao.consultarVendasDiarias(fs.retirarFormatacaoData(campoData1Faturamento.getText()), fs.retirarFormatacaoData(campoData2Faturamento.getText()));
        for (int i = 0; i < orcs.size(); i++) {
            barra.setValue(Double.parseDouble(orcs.get(i).getOrcamento_preco_pecas()) + Double.parseDouble(orcs.get(i).getOrcamento_preco_servicos()), orcs.get(i).getOrcamento_data(), "Venda de peças e serviços");
        }
        JFreeChart graficoBarra = ChartFactory.createBarChart("Gráfico do faturamento diário", "Dia", "Faturamento", barra, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel painelzadaB = new ChartPanel(graficoBarra);
        jfBarra.setIconImage(icon);
        jfBarra.setTitle("Faturamento diário");
        jfBarra.add(painelzadaB);
        jfBarra.setSize(950, 700);
        jfBarra.setLocationRelativeTo(null);
        jfBarra.setVisible(true);
    }//GEN-LAST:event_abrirGraficoBarraFaturamentoDiario

    private void tecladaDataFaturamento(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tecladaDataFaturamento
        if (evt.getComponent().getName().equals("1")) {
            if ("\b".equals(Character.toString(evt.getKeyChar()))) {
                campoData1Faturamento.setText(fs.apagar(campoData1Faturamento.getText(), evt.getComponent().getName()));
            }
            String txtV = vs.dataOntem(evt, campoData1Faturamento.getText());
            if (txtV == "") {
                txtErroFaturamento.setForeground(new Color(240, 240, 240));
            } else if (txtV.endsWith("números.")) {
                campoData1Faturamento.setText(campoData1Faturamento.getText().substring(0, campoData1Faturamento.getText().length() - 1));
            } else {
                txtErroFaturamento.setText(txtV);
                if (txtV.endsWith(".")) {
                    txtErroFaturamento.setForeground(new Color(255, 0, 0));
                } else {
                    txtErroFaturamento.setForeground(new Color(0, 160, 40));
                }
            }
            if (campoData1Faturamento.getText().length() > 10) {
                int calc = campoData1Faturamento.getText().length() - 10;
                campoData1Faturamento.setText(campoData1Faturamento.getText().substring(0, campoData1Faturamento.getText().length() - calc));
            }
            String txtF = fs.data(campoData1Faturamento.getText());
            campoData1Faturamento.setText(txtF);
        } else {
            if ("\b".equals(Character.toString(evt.getKeyChar()))) {
                campoData2Faturamento.setText(fs.apagar(campoData2Faturamento.getText(), evt.getComponent().getName()));
            }
            String txtV = vs.dataOntem(evt, campoData2Faturamento.getText());
            if (txtV == "") {
                txtErroFaturamento.setForeground(new Color(240, 240, 240));
            } else if (txtV.endsWith("números.")) {
                campoData2Faturamento.setText(campoData2Faturamento.getText().substring(0, campoData2Faturamento.getText().length() - 1));
            } else {
                txtErroFaturamento.setText(txtV);
                if (txtV.endsWith(".")) {
                    txtErroFaturamento.setForeground(new Color(255, 0, 0));
                } else {
                    txtErroFaturamento.setForeground(new Color(0, 160, 40));
                }
            }
            if (campoData2Faturamento.getText().length() > 10) {
                int calc = campoData2Faturamento.getText().length() - 10;
                campoData2Faturamento.setText(campoData2Faturamento.getText().substring(0, campoData2Faturamento.getText().length() - calc));
            }
            String txtF = fs.data(campoData2Faturamento.getText());
            campoData2Faturamento.setText(txtF);
        }
    }//GEN-LAST:event_tecladaDataFaturamento

    private void tecladaDataOs(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tecladaDataOs
        if (evt.getComponent().getName().equals("1")) {
            if ("\b".equals(Character.toString(evt.getKeyChar()))) {
                campoData1Os.setText(fs.apagar(campoData1Os.getText(), evt.getComponent().getName()));
            }
            String txtV = vs.dataOntem(evt, campoData1Os.getText());
            if (txtV == "") {
                txtErroOs.setForeground(new Color(240, 240, 240));
            } else if (txtV.endsWith("números.")) {
                campoData1Os.setText(campoData1Os.getText().substring(0, campoData1Os.getText().length() - 1));
            } else {
                txtErroOs.setText(txtV);
                if (txtV.endsWith(".")) {
                    txtErroOs.setForeground(new Color(255, 0, 0));
                } else {
                    txtErroOs.setForeground(new Color(0, 160, 40));
                }
            }
            if (campoData1Os.getText().length() > 10) {
                int calc = campoData1Os.getText().length() - 10;
                campoData1Os.setText(campoData1Os.getText().substring(0, campoData1Os.getText().length() - calc));
            }
            String txtF = fs.data(campoData1Os.getText());
            campoData1Os.setText(txtF);
        } else {
            if ("\b".equals(Character.toString(evt.getKeyChar()))) {
                campoData2Os.setText(fs.apagar(campoData2Os.getText(), evt.getComponent().getName()));
            }
            String txtV = vs.dataOntem(evt, campoData2Os.getText());
            if (txtV == "") {
                txtErroOs.setForeground(new Color(240, 240, 240));
            } else if (txtV.endsWith("números.")) {
                campoData2Os.setText(campoData2Os.getText().substring(0, campoData2Os.getText().length() - 1));
            } else {
                txtErroOs.setText(txtV);
                if (txtV.endsWith(".")) {
                    txtErroOs.setForeground(new Color(255, 0, 0));
                } else {
                    txtErroOs.setForeground(new Color(0, 160, 40));
                }
            }
            if (campoData2Os.getText().length() > 10) {
                int calc = campoData2Os.getText().length() - 10;
                campoData2Os.setText(campoData2Os.getText().substring(0, campoData2Os.getText().length() - calc));
            }
            String txtF = fs.data(campoData2Os.getText());
            campoData2Os.setText(txtF);
        }
    }//GEN-LAST:event_tecladaDataOs

    private void abrirGraficoBarraFaturamentoTotal(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirGraficoBarraFaturamentoTotal
        if (!vazioFaturamento()){
            if (!erroFaturamento()){
                btnClicado(evt);
                    JFrame jfBarra = new JFrame();
                    DefaultCategoryDataset barra = new DefaultCategoryDataset();
                    OrcamentoDAO orcdao = new OrcamentoDAO();
                    Orcamento orc = new Orcamento();
                    orc = orcdao.consultarVendasTotais(fs.retirarFormatacaoData(campoData1Faturamento.getText()), fs.retirarFormatacaoData(campoData2Faturamento.getText()));
                    barra.setValue(Double.parseDouble(orc.getOrcamento_preco_pecas()), "Peças", "Venda total de peças");
                    barra.setValue(Double.parseDouble(orc.getOrcamento_preco_servicos()), "Serviços", "Venda total de serviços");
                    JFreeChart graficoBarra = ChartFactory.createBarChart("Gráfico do faturamento total", "Peças ou serviços", "Faturamento", barra, PlotOrientation.VERTICAL, true, true, false);
                    ChartPanel painelzadaB = new ChartPanel(graficoBarra);
                    jfBarra.setIconImage(icon);
                    jfBarra.setTitle("Faturamento total");
                    jfBarra.add(painelzadaB);
                    jfBarra.setSize(950, 700);
                    jfBarra.setLocationRelativeTo(null);
                    jfBarra.setVisible(true);
            }
        }
    }//GEN-LAST:event_abrirGraficoBarraFaturamentoTotal

    private void abrirGraficoPizzaFaturamentoTotal(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirGraficoPizzaFaturamentoTotal
        if (!vazioFaturamento()){
            if (!erroFaturamento()){
                btnClicado(evt);
                    JFrame jfPizaa = new JFrame();
                    DefaultPieDataset pizza = new DefaultPieDataset();
                    OrcamentoDAO orcdao = new OrcamentoDAO();
                    Orcamento orc = new Orcamento();
                    orc = orcdao.consultarVendasTotais(fs.retirarFormatacaoData(campoData1Faturamento.getText()), fs.retirarFormatacaoData(campoData2Faturamento.getText()));
                    pizza.setValue("Peças", Double.parseDouble(orc.getOrcamento_preco_pecas()));
                    pizza.setValue("Serviços", Double.parseDouble(orc.getOrcamento_preco_servicos()));
                    JFreeChart graficoPizza = ChartFactory.createPieChart("Faturamento entre " + campoData1Faturamento.getText() + " e " + campoData2Faturamento.getText(), pizza, true, true, false);
                    ChartPanel painelzadaP = new ChartPanel(graficoPizza);
                    jfPizaa.setIconImage(icon);
                    jfPizaa.setTitle("Faturamento total");
                    jfPizaa.add(painelzadaP);
                    jfPizaa.setSize(950, 700);
                    jfPizaa.setLocationRelativeTo(null);
                    jfPizaa.setVisible(true);
            }
        }
    }//GEN-LAST:event_abrirGraficoPizzaFaturamentoTotal

    private void abrirGraficoPizzaOs(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirGraficoPizzaOs
        if (!vazioOs()){
            if (!erroOs()){
                btnClicado(evt);
                JFrame jfPizaa = new JFrame();
                DefaultPieDataset pizza = new DefaultPieDataset();
                OsDAO osdao = new OsDAO();
                OS os = new OS();
                os = osdao.consultaOsSaidaEEntrada(fs.retirarFormatacaoData(campoData1Os.getText()), fs.retirarFormatacaoData(campoData2Os.getText()));
                pizza.setValue("Saíram", Integer.parseInt(os.getQtdConcluida()));
                pizza.setValue("Entraram", Integer.parseInt(os.getQtdOs()));
                JFreeChart graficoPizza = ChartFactory.createPieChart("Entrada e saída de veículos entre " + campoData1Os.getText() + " e " + campoData2Os.getText(), pizza, true, true, false);
                ChartPanel painelzadaP = new ChartPanel(graficoPizza);
                jfPizaa.setIconImage(icon);
                jfPizaa.setTitle("Entrada e saída de veículos");
                jfPizaa.add(painelzadaP);
                jfPizaa.setSize(950, 700);
                jfPizaa.setLocationRelativeTo(null);
                jfPizaa.setVisible(true);
            }          
        } 
    }//GEN-LAST:event_abrirGraficoPizzaOs

    private void abrirGraficoBarraSaida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirGraficoBarraSaida
        if (!vazioOs()){
            if (!erroOs()){
                btnClicado(evt);
                JFrame jfPizaa = new JFrame();
                DefaultCategoryDataset barra = new DefaultCategoryDataset();
                OsDAO osdao = new OsDAO();
                List<OS> oss = new ArrayList<>();
                oss = osdao.consultaOsSaidaDiaria(fs.retirarFormatacaoData(campoData1Os.getText()), fs.retirarFormatacaoData(campoData2Os.getText()));
                for (int i = 0; i < oss.size(); i++) {
                    barra.setValue(Integer.parseInt(oss.get(i).getQtdOs()), oss.get(i).getOsDataSaida(), "Saída");
                }
                JFreeChart graficoBarra = ChartFactory.createBarChart("Gráfico da saída de veículos", "Dia", "Quantidade de veículos", barra, PlotOrientation.VERTICAL, true, true, false);
                ChartPanel painelzadaB = new ChartPanel(graficoBarra);
                jfPizaa.setIconImage(icon);
                jfPizaa.setTitle("Saída de veículos");
                jfPizaa.add(painelzadaB);
                jfPizaa.setSize(950, 700);
                jfPizaa.setLocationRelativeTo(null);
                jfPizaa.setVisible(true);
            }
        }
    }//GEN-LAST:event_abrirGraficoBarraSaida

    private void abrirGraficoBarraEntrada(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirGraficoBarraEntrada
        if (!vazioOs()){
            if (!erroOs()){
                btnClicado(evt);
                JFrame jfPizaa = new JFrame();
                DefaultCategoryDataset barra = new DefaultCategoryDataset();
                OsDAO osdao = new OsDAO();
                List<OS> oss = new ArrayList<>();
                oss = osdao.consultaOsEntradaDiaria(fs.retirarFormatacaoData(campoData1Os.getText()), fs.retirarFormatacaoData(campoData2Os.getText()));
                for (int i = 0; i < oss.size(); i++) {
                    barra.setValue(Integer.parseInt(oss.get(i).getQtdOs()), oss.get(i).getOsDataEntrada(), "Entrada");
                }
                JFreeChart graficoBarra = ChartFactory.createBarChart("Gráfico da entarda de veículos", "Dia", "Quantidade de veículos", barra, PlotOrientation.VERTICAL, true, true, false);
                ChartPanel painelzadaB = new ChartPanel(graficoBarra);
                jfPizaa.setIconImage(icon);
                jfPizaa.setTitle("Entrada de veículos");
                jfPizaa.add(painelzadaB);
                jfPizaa.setSize(950, 700);
                jfPizaa.setLocationRelativeTo(null);
                jfPizaa.setVisible(true);
            }
        }
    }//GEN-LAST:event_abrirGraficoBarraEntrada

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RELATORIO_TELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RELATORIO_TELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RELATORIO_TELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RELATORIO_TELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RELATORIO_TELA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIrCadastroOS;
    private javax.swing.JButton btnIrCadastroOS1;
    private javax.swing.JButton btnIrCadastroOS4;
    private javax.swing.JButton btnIrCadastroOS5;
    private javax.swing.JButton btnIrCadastroOS6;
    private javax.swing.JButton btnIrCadastroOS7;
    private javax.swing.JButton btnIrCadastroOS8;
    private javax.swing.JButton btnIrCadastroOS9;
    private javax.swing.JButton btnIrConsultaOS;
    private javax.swing.JButton btnIrOS;
    private javax.swing.JButton btnIrRelatorios;
    private javax.swing.JButton btnIrUsuario;
    private javax.swing.JTextField campoData1Faturamento;
    private javax.swing.JTextField campoData1Os;
    private javax.swing.JTextField campoData2Faturamento;
    private javax.swing.JTextField campoData2Os;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel painelCRUD;
    private javax.swing.JPanel painelFormularioConsulta;
    private javax.swing.JPanel painelOpcoesCRUD;
    private javax.swing.JPanel painelSecoes;
    private javax.swing.JLabel txtErroFaturamento;
    private javax.swing.JLabel txtErroOs;
    // End of variables declaration//GEN-END:variables
    
    private void btnClicado(java.awt.event.MouseEvent evt) {
        /*
            MÉTODO RESPONSÁVEL POR MUDAR A COR DE FUNDO DO BOTAO QUANDO FOR CLICADO
         */
        evt.getComponent().setBackground(new Color(100, 0, 0));
        new Timer().schedule(
                new TimerTask() {
            @Override
            public void run() {
                evt.getComponent().setBackground(new Color(204, 0, 0));
            }
        }, 50);
    }
    
    private boolean erroFaturamento(){
        boolean temErro = false;
        if (txtErroFaturamento.getForeground().getRed() == 255){
            temErro = true;
        } 
        return temErro;
    }
    
    private boolean erroOs(){
        boolean temErro = false;
        if (txtErroOs.getForeground().getRed() == 255){
            temErro = true;
        } 
        return temErro;
    }
    
    private boolean vazioFaturamento(){
        boolean vazio = false;
        if (campoData1Faturamento.getText().equals("") || campoData2Faturamento.getText().equals("")){
            vazio = true;
        }
        return vazio;
    }
    
    private boolean vazioOs(){ 
        boolean vazio = false;
        if (campoData1Os.getText().equals("") || campoData2Os.getText().equals("")){
            vazio = true;
        }
        return vazio;
    }
}
