/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pif.desktop.TELAS;

import pif.desktop.Classes.USER_LOGADO;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import javax.imageio.ImageIO;
import pif.desktop.Classes.Colab;
import pif.desktop.Classes.Contato;
import pif.desktop.Classes.FormatacaoStrings;
import pif.desktop.Classes.VerificacaoStrings;
import pif.desktop.DAO.OsDAO;

/**
 *
 * @author arthu
 */
public class USER_TELA extends javax.swing.JFrame {

    Image icon;
    private TelaUtils u = new TelaUtils();
    private FormatacaoStrings fs = new FormatacaoStrings();
    private VerificacaoStrings vs = new VerificacaoStrings();

//    private static RUD_EQUIP_TELA RUD_EQUIP = new RUD_EQUIP_TELA();
//    private static C_EQUIP_TELA C_EQUIP = new C_EQUIP_TELA();
//
//    public static RUD_TEC_TELA RUD_TEC = new RUD_TEC_TELA();
//    public static C_TEC_TELA C_TEC = new C_TEC_TELA();
//
//    public static RUD_CLIENTE_TELA RUD_CLIENTE = new RUD_CLIENTE_TELA();
//    public static C_CLIENTE_TELA C_CLIENTE = new C_CLIENTE_TELA();
    /**
     * Creates new form CADASTRAR_OS
     */
    public USER_TELA() {
        try {
            icon = ImageIO.read(getClass().getResource("/resources/icon.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        initComponents();
        painelSecoes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 40, 40)), "Seja bem-vindo(a) " + USER_LOGADO.getCOLAB_NOME() + "! Para qual seção deseja ir?", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)));
        campoBairro.setText(USER_LOGADO.getCOLAB_BAIRRO());
        campoCep.setText(fs.botarCep(USER_LOGADO.getCOLAB_CEP()));
        campoCidade.setText(USER_LOGADO.getCOLAB_CIDADE());
        campoCpfnj.setText(fs.botarCpfOuCnpj(USER_LOGADO.getCOLAB_CPF()));
        campoDataNasc.setText(fs.botarData(USER_LOGADO.getCOLAB_DATA_NASCIMENTO()));
        campoEmail.setText(USER_LOGADO.getCOLAB_CONTATO_EMAIL());
        campoLograd.setText(USER_LOGADO.getCOLAB_LOGRAD());
        campoLogradComp.setText(USER_LOGADO.getCOLAB_LOGRAD_COMP());
        campoLogradNum.setText(USER_LOGADO.getCOLAB_LOGRAD_NUM());
        campoNomeRazao.setText(USER_LOGADO.getCOLAB_NOME());
        campoNumTel1.setText(fs.botarTelefone(USER_LOGADO.getCOLAB_CONTATO_NUM_TEL1()));
        campoNumTel2.setText(fs.botarTelefone(USER_LOGADO.getCOLAB_CONTATO_NUM_TEL2()));
        campoRgIe.setText(USER_LOGADO.getCOLAB_RG());
        campoSobrenomeFantasia.setText(USER_LOGADO.getCOLAB_SOBRENOME());
        caixaCombinacaoEstado.setSelectedIndex(vs.verificarEstado(USER_LOGADO.getCOLAB_ESTADO()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        painelSecoes = new javax.swing.JPanel();
        btnIrOS = new javax.swing.JButton();
        btnIrUsuario = new javax.swing.JButton();
        painelInfoUser = new javax.swing.JPanel();
        titleNomeRazao = new javax.swing.JLabel();
        campoNomeRazao = new javax.swing.JTextField();
        titleSobrenomeFantasia = new javax.swing.JLabel();
        campoSobrenomeFantasia = new javax.swing.JTextField();
        titleRgIe = new javax.swing.JLabel();
        campoRgIe = new javax.swing.JTextField();
        campoCpfnj = new javax.swing.JTextField();
        titleCpfnj = new javax.swing.JLabel();
        painelContato = new javax.swing.JPanel();
        titleEmail = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        titleNumTel1 = new javax.swing.JLabel();
        campoNumTel1 = new javax.swing.JTextField();
        titleNumTel2 = new javax.swing.JLabel();
        campoNumTel2 = new javax.swing.JTextField();
        painelEndereco = new javax.swing.JPanel();
        titleEstado = new javax.swing.JLabel();
        titleCep = new javax.swing.JLabel();
        campoCep = new javax.swing.JTextField();
        titleCidade = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        caixaCombinacaoEstado = new javax.swing.JComboBox<>();
        titleBairro = new javax.swing.JLabel();
        campoBairro = new javax.swing.JTextField();
        titleLograd = new javax.swing.JLabel();
        campoLograd = new javax.swing.JTextField();
        titleLogradNum = new javax.swing.JLabel();
        campoLogradNum = new javax.swing.JTextField();
        titleLogradComp = new javax.swing.JLabel();
        campoLogradComp = new javax.swing.JTextField();
        titleDataNasc = new javax.swing.JLabel();
        campoDataNasc = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setIconImage(icon);
        setMinimumSize(new java.awt.Dimension(1368, 768));
        setPreferredSize(new java.awt.Dimension(1368, 768));

        painelSecoes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 40, 40)), "Para qual seção deseja ir?", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        btnIrOS.setBackground(new java.awt.Color(204, 0, 0));
        btnIrOS.setForeground(new java.awt.Color(255, 255, 255));
        btnIrOS.setText("Ordem de serviço");
        btnIrOS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(130, 0, 0), new java.awt.Color(130, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnIrOS.setContentAreaFilled(false);
        btnIrOS.setFocusPainted(false);
        btnIrOS.setOpaque(true);
        btnIrOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                irCadastroOS(evt);
            }
        });

        btnIrUsuario.setBackground(new java.awt.Color(100, 0, 0));
        btnIrUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnIrUsuario.setText("Suas informações");
        btnIrUsuario.setToolTipText("");
        btnIrUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 0, 0)));
        btnIrUsuario.setContentAreaFilled(false);
        btnIrUsuario.setFocusPainted(false);
        btnIrUsuario.setOpaque(true);

        javax.swing.GroupLayout painelSecoesLayout = new javax.swing.GroupLayout(painelSecoes);
        painelSecoes.setLayout(painelSecoesLayout);
        painelSecoesLayout.setHorizontalGroup(
            painelSecoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSecoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIrOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btnIrUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelSecoesLayout.setVerticalGroup(
            painelSecoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSecoesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(painelSecoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIrOS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIrUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        painelInfoUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 40, 0)));

        titleNomeRazao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleNomeRazao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleNomeRazao.setText("Seu CPF:");

        campoNomeRazao.setBackground(new java.awt.Color(240, 240, 240));
        campoNomeRazao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoNomeRazao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoNomeRazao.setText("jTextField1");
        campoNomeRazao.setBorder(null);
        campoNomeRazao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoNomeRazao.setEnabled(false);

        titleSobrenomeFantasia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleSobrenomeFantasia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSobrenomeFantasia.setText("Seu RG:");

        campoSobrenomeFantasia.setBackground(new java.awt.Color(240, 240, 240));
        campoSobrenomeFantasia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoSobrenomeFantasia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoSobrenomeFantasia.setText("jTextField1");
        campoSobrenomeFantasia.setBorder(null);
        campoSobrenomeFantasia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoSobrenomeFantasia.setEnabled(false);

        titleRgIe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleRgIe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleRgIe.setText("Seu sobrenome:");

        campoRgIe.setBackground(new java.awt.Color(240, 240, 240));
        campoRgIe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoRgIe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoRgIe.setText("jTextField1");
        campoRgIe.setBorder(null);
        campoRgIe.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoRgIe.setEnabled(false);

        campoCpfnj.setBackground(new java.awt.Color(240, 240, 240));
        campoCpfnj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoCpfnj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoCpfnj.setText("jTextField1");
        campoCpfnj.setBorder(null);
        campoCpfnj.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoCpfnj.setEnabled(false);

        titleCpfnj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleCpfnj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCpfnj.setText("Seu nome:");

        painelContato.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 40, 40)), "Seu contato", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        titleEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEmail.setText("Seu email:");

        campoEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        campoEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoEmail.setEnabled(false);

        titleNumTel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleNumTel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleNumTel1.setText("Seu número de telefone principal:");

        campoNumTel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoNumTel1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoNumTel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        campoNumTel1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoNumTel1.setEnabled(false);
        campoNumTel1.setName("tel1"); // NOI18N

        titleNumTel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleNumTel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleNumTel2.setText("Seu número de telefone alternativo:");

        campoNumTel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoNumTel2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoNumTel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        campoNumTel2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoNumTel2.setEnabled(false);
        campoNumTel2.setName("tel2"); // NOI18N

        javax.swing.GroupLayout painelContatoLayout = new javax.swing.GroupLayout(painelContato);
        painelContato.setLayout(painelContatoLayout);
        painelContatoLayout.setHorizontalGroup(
            painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelContatoLayout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addGroup(painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelContatoLayout.createSequentialGroup()
                        .addComponent(titleEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelContatoLayout.createSequentialGroup()
                        .addGroup(painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleNumTel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleNumTel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoNumTel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNumTel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        painelContatoLayout.setVerticalGroup(
            painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelContatoLayout.createSequentialGroup()
                .addGroup(painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleEmail)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleNumTel1)
                    .addComponent(campoNumTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleNumTel2)
                    .addComponent(campoNumTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        painelEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 40, 40)), "Seu endereço", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        titleEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEstado.setText("Estado:");

        titleCep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleCep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCep.setText("CEP:");

        campoCep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoCep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoCep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        campoCep.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoCep.setEnabled(false);
        campoCep.setName("cep"); // NOI18N

        titleCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleCidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCidade.setText("Cidade:");

        campoCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoCidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoCidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        campoCidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoCidade.setEnabled(false);

        caixaCombinacaoEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caixaCombinacaoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        caixaCombinacaoEstado.setEnabled(false);
        caixaCombinacaoEstado.setFocusable(false);

        titleBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleBairro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleBairro.setText("Bairro:");

        campoBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoBairro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoBairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        campoBairro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoBairro.setEnabled(false);

        titleLograd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleLograd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLograd.setText("Logradouro:");

        campoLograd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoLograd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoLograd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        campoLograd.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoLograd.setEnabled(false);

        titleLogradNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleLogradNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLogradNum.setText("N°:");

        campoLogradNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoLogradNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoLogradNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        campoLogradNum.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoLogradNum.setEnabled(false);

        titleLogradComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleLogradComp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLogradComp.setText("Complemento:");

        campoLogradComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoLogradComp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoLogradComp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        campoLogradComp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoLogradComp.setEnabled(false);

        javax.swing.GroupLayout painelEnderecoLayout = new javax.swing.GroupLayout(painelEndereco);
        painelEndereco.setLayout(painelEnderecoLayout);
        painelEnderecoLayout.setHorizontalGroup(
            painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEnderecoLayout.createSequentialGroup()
                        .addComponent(titleLogradNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoLogradNum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(398, 398, 398)
                        .addComponent(titleLogradComp)
                        .addGap(18, 18, 18)
                        .addComponent(campoLogradComp, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(painelEnderecoLayout.createSequentialGroup()
                            .addComponent(titleLograd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campoLograd))
                        .addGroup(painelEnderecoLayout.createSequentialGroup()
                            .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelEnderecoLayout.createSequentialGroup()
                                    .addComponent(titleCidade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painelEnderecoLayout.createSequentialGroup()
                                    .addComponent(titleEstado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(caixaCombinacaoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(342, 342, 342)
                            .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(titleBairro, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(titleCep, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoCep)
                                .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        painelEnderecoLayout.setVerticalGroup(
            painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoLayout.createSequentialGroup()
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleEstado)
                    .addComponent(caixaCombinacaoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleCep)
                    .addComponent(campoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleCidade)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleBairro)
                    .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLograd)
                    .addComponent(campoLograd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titleLogradComp)
                        .addComponent(campoLogradComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titleLogradNum)
                        .addComponent(campoLogradNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titleDataNasc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleDataNasc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleDataNasc.setText("Sua data de nascimento:");

        campoDataNasc.setBackground(new java.awt.Color(240, 240, 240));
        campoDataNasc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoDataNasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoDataNasc.setText("jTextField1");
        campoDataNasc.setBorder(null);
        campoDataNasc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoDataNasc.setEnabled(false);

        javax.swing.GroupLayout painelInfoUserLayout = new javax.swing.GroupLayout(painelInfoUser);
        painelInfoUser.setLayout(painelInfoUserLayout);
        painelInfoUserLayout.setHorizontalGroup(
            painelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoUserLayout.createSequentialGroup()
                .addGroup(painelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInfoUserLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titleNomeRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoNomeRazao))
                    .addGroup(painelInfoUserLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelEndereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelInfoUserLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(titleSobrenomeFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleRgIe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleCpfnj, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGroup(painelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelInfoUserLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(painelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoDataNasc)
                                    .addComponent(campoCpfnj)
                                    .addComponent(campoRgIe)))
                            .addGroup(painelInfoUserLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(campoSobrenomeFantasia)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelInfoUserLayout.setVerticalGroup(
            painelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoUserLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(painelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleNomeRazao)
                    .addComponent(campoNomeRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleSobrenomeFantasia)
                    .addComponent(campoSobrenomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleCpfnj)
                    .addComponent(campoCpfnj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleRgIe)
                    .addComponent(campoRgIe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleDataNasc)
                    .addComponent(campoDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(painelContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(painelSecoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelInfoUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelInfoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void irCadastroOS(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irCadastroOS
        u.irDePara(this, C_OS_TELA.getC_OS());
    }//GEN-LAST:event_irCadastroOS

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(USER_TELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(USER_TELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(USER_TELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(USER_TELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
    }

    //<editor-fold defaultstate="collapsed" desc="Coisas do javax">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIrOS;
    private javax.swing.JButton btnIrUsuario;
    private javax.swing.JComboBox<String> caixaCombinacaoEstado;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCep;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoCpfnj;
    private javax.swing.JTextField campoDataNasc;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoLograd;
    private javax.swing.JTextField campoLogradComp;
    private javax.swing.JTextField campoLogradNum;
    private javax.swing.JTextField campoNomeRazao;
    private javax.swing.JTextField campoNumTel1;
    private javax.swing.JTextField campoNumTel2;
    private javax.swing.JTextField campoRgIe;
    private javax.swing.JTextField campoSobrenomeFantasia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel painelContato;
    private javax.swing.JPanel painelEndereco;
    private javax.swing.JPanel painelInfoUser;
    private javax.swing.JPanel painelSecoes;
    private javax.swing.JLabel titleBairro;
    private javax.swing.JLabel titleCep;
    private javax.swing.JLabel titleCidade;
    private javax.swing.JLabel titleCpfnj;
    private javax.swing.JLabel titleDataNasc;
    private javax.swing.JLabel titleEmail;
    private javax.swing.JLabel titleEstado;
    private javax.swing.JLabel titleLograd;
    private javax.swing.JLabel titleLogradComp;
    private javax.swing.JLabel titleLogradNum;
    private javax.swing.JLabel titleNomeRazao;
    private javax.swing.JLabel titleNumTel1;
    private javax.swing.JLabel titleNumTel2;
    private javax.swing.JLabel titleRgIe;
    private javax.swing.JLabel titleSobrenomeFantasia;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>

    private void btnClicado(java.awt.event.MouseEvent evt) {
        evt.getComponent().setBackground(new Color(100, 0, 0));
        new Timer().schedule(
                new TimerTask() {
            @Override
            public void run() {
                evt.getComponent().setBackground(new Color(204, 0, 0));
            }
        }, 50);
    }
}
